export default {
    'biz.util.open': {
        'chat': 0,
        'call': 0,
        'profile': 0,
        'contactAdd': 4,
        'friendAdd': 4,
    },

    'device.accelerometer.watchShake': 0,
    'device.accelerometer.clearShake': 0,
    'device.notification.vibrate': 0,
    'biz.contact.choose': 0,
    'biz.navigation.setLeft': 0,
    'biz.navigation.setTitle': 0,
    'biz.navigation.setRight': 0,
    'biz.navigation.back': 0,
    'device.notification.alert': 0,
    'device.notification.confirm': 0,
    'device.notification.prompt': 0,
    'biz.util.share': 0,
    'biz.util.ut': 0,
    'biz.util.datepicker': 0,
    'biz.util.timepicker': 0,

    'runtime.info': 1,
    'device.geolocation.get': 1,
    'device.notification.toast': 1,
    'device.notification.showPreloader': 1,
    'device.notification.hidePreloader': 1,
    'biz.util.uploadImage': 1,
    'biz.util.previewImage': 1,

    'device.connection.getNetworkType': 2,
    'biz.util.qrcode': 2,
    'device.notification.actionSheet': 2,
    'ui.input.plain': 2,

    'biz.ding.post': 3,
    'biz.telephone.call': 3,
    'biz.chat.chooseConversation': 3,

    'biz.contact.createGroup': 4,
    'biz.util.datetimepicker': 4,

    'biz.util.chosen': 5,
    'device.base.getUUID': 5,
    'device.base.getInterface': 5,
    'device.launcher.checkInstalledApps': 5,
    'device.launcher.launchApp': 5,
    'runtime.permission.requestAuthCode': 5,
    'runtime.permission.requestJsApis': 5,
    'ui.pullToRefresh.enable': 5,
    'ui.pullToRefresh.stop': 5,
    'ui.pullToRefresh.disable': 5,
    'ui.webViewBounce.disable': 5,
    'ui.webViewBounce.enable': 5,
}